version: "3.9" # Essa é a versão do formato do Docker Compose

services:
  db:
    image: postgres:15 # Versão 15 do PostgreSQL
    restart: always # Vai reiniciar automaticamente em caso de alguma falha
    environment:  # Definir as variáveis de ambiente para configurar o banco
      POSTGRES_USER: postgres # Usuário do banco
      POSTGRES_PASSWORD: senha123 # Senha do banco
      POSTGRES_DB: app_development # Nome do banco padrão
    volumes:  # Persistência de dados entre reinícios
      - db-data:/var/lib/postgresql/data
    networks: # Rede onde o serviço vai operar
      - backend-network
  
  backend:
    build:
      context: ./backend  # Diretório onde o Dockerfile do Rails está
      dockerfile: Dockerfile  # Nome do Dockerfile que vai ser usado
      args:
        # Passar o SECRET_KEY_BASE do .env para dentro do build
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    restart: always 
    volumes:
      - ./backend:/rails  # Vai montar o código do host em /app dentro do conteiner
    working_dir: /rails
    ports:
      - "3000:3000"   # Vai mapear a porta 3000 do host para o container
    env_file:
      # Vai carregar .env para runtime (DATABASE_URL, RAILS_ENV, SECRET_KEY_BASE, etc)
      - ./.env
    environment:  # Variáveis de ambiente para o Rails
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: postgres://postgres:senha123@db:5432/app_development
      RAILS_ENV: development  # Define o ambiente Rails como "development"
    depends_on:
      - db  # Vai garantir que o banco inicie antes do Rails
    networks:
      - backend-network   # Mesma rede usada pelo serviço de banco
  
volumes:
  db-data:  # Volume nomeado para armazenamento dos dados do PostgreSQL, vai criar automaticamente com o nome padrão

networks:
  backend-network:  # Rede dedicada para comunicação entre backend e db, novamente será criado de maneira padrão

